[custom]
;自定义规则集 - 屏蔽的网站强制直连（大陆无法访问）
ruleset=DIRECT,rules/block_sites.list

;国内网站直连
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list

;其余流量走代理
ruleset=🚀 节点选择,[]MATCH

enable_rule_generator=true
overwrite_original_rules=true
